project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx:
    reference-doc: custom-reference.docx
  jats: default
  agu-pdf: default



